# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='nou',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.Person'),
        ),
        migrations.AddField(
            model_name='nou',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.Quote'),
        ),
    ]
