# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0003_auto_20161119_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nou',
            name='date',
            field=models.DateField(),
        ),
    ]
