# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0005_remove_nou_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nou',
            name='date',
            field=models.DateField(default=datetime.date(2016, 11, 19)),
            preserve_default=False,
        ),
    ]
