# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0007_auto_20161120_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_created', models.BooleanField()),
                ('num_events_inserted', models.IntegerField()),
                ('num_events_skipped', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.Person')),
            ],
        ),
    ]
