# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0009_auto_20161202_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactivity',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logactivity',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
