# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0010_auto_20161202_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactivity',
            name='error',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
