# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0011_logactivity_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactivity',
            name='error',
            field=models.CharField(max_length=128),
        ),
    ]
